### ISSUE TITLE
Schedule Change Month Functionality

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/prescription-app#35]
Schedule doesn't change month when you click the arrows.

![2018-12-17 11 32 04](https://user-images.githubusercontent.com/2746248/50084599-70a23180-01ef-11e9-9a08-53f4d495cb98.gif)

**Comment by Charlielancaster** [comment]
https://stackoverflow.com/questions/46106037/vuex-computed-property-name-was-assigned-to-but-it-has-no-setter

Apparently needs a setter (not sure what that is right now... I assume that it doesn't know what to do with the data)

**Comment by michaelfitzhavey** [comment]
Bang on. In the end the solution was just having `dateContext` as a _data_ property rather than a _computed_ one (which since it's computed with a function can't be set to another value)

fixed here: #44
