### ISSUE TITLE
Add Information Module stuck disabled

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/prescription-app#36]
can't add information module with 1 fact and an image:

![image](https://user-images.githubusercontent.com/2746248/50087766-f4145080-01f8-11e9-88d2-bc46d973ca71.png)

**Comment by Charlielancaster** [comment]
isNewModuleValid() this.type was missing a ! in ModuleCreateModal.vue line 171

isNewModuleValid() {
			if (!this.name ||
				!this.repeatDays ||
				!this.type
			) return false;
			if (this.type === 'survey') {
				if (this.questions.length === 0) return false;
			}
			if (this.type === 'information') {
				if (this.information.length === 0) return false;
			}
			return true;
		}

**Comment by Charlielancaster** [comment]
https://github.com/holistic-web/prescription-app/pull/38
